### ISSUE TITLE
Updating line item quantity doesn't recalculate discounts

### ISSUE THREAD

**Issue by ckepper** [django-oscar/django-oscar-api#82]
This issue might be related to #78.

Essentially, I am just sending a PUT request to update the quantity of a line item as explained in the example usage. However, after updating the line item quantity, discounts are not recalculated and in the response price_excl_tax and price_excl_tax_excl_discounts are equal. I would expect that count based offers are applied after updating the quantity.

Only when I request the whole basket again, the line items are updated.

**Comment by maerteijn** [comment]
Hi @ckepper. Discounts are calculated by applying offers on the complete basket, not just per line. So this is a bit of an edge-case as we follow the way oscar caclulates the discounts and offers on a basket.

Do you mean btw that `price_excl_tax` and `price_excl_tax_excl_discounts ` are not automatic recalculated on your client when not retrieving the basket again? These fields are only available in the basket right?

**Comment by ckepper** [comment]
I am aware that this might be an edge case and I know that Oscar calculates discounts on the basket and not on a single line item.

What I found confusing was that I received a response to the `PUT` request that included `price_excl_tax_excl_discounts` but the value was incorrect. I would have expected that the response shows either the correct value (with discount applied) or no discount field at all. Hope that makes sense.

Here is the output of the `PUT` request:
```javascript
{
  "url": "https://localhost/shop/api/v1/baskets/37/lines/31/",
  "product": "https://localhost/shop/api/v1/products/8/",
  "quantity": 100,
  "attributes": [],
  "price_currency": "USD",
  "price_excl_tax": 299,
  "price_incl_tax": 299,
  "price_incl_tax_excl_discounts": 299,
  "price_excl_tax_excl_discounts": 299,
  "is_tax_known": false,
  "warning": null,
  "basket": "https://localhost/shop/api/v1/baskets/37/",
  "stockrecord": "https://localhost/shop/api/v1/stockrecords/8/",
  "date_created": "2016-11-13T00:17:06.447193Z"
}
```

The call to the basket lines however reveals that there is a discount on the product:
```javascript
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "url": "https://localhost/shop/api/v1/baskets/37/lines/31/",
      "product": "https://localhost/shop/api/v1/products/8/",
      "quantity": 100,
      "attributes": [],
      "price_currency": "USD",
      "price_excl_tax": 269.1,
      "price_incl_tax": 269.1,
      "price_incl_tax_excl_discounts": 299,
      "price_excl_tax_excl_discounts": 299,
      "is_tax_known": false,
      "warning": null,
      "basket": "https://localhost/shop/api/v1/baskets/37/",
      "stockrecord": "https://localhost/shop/api/v1/stockrecords/8/",
      "date_created": "2016-11-13T00:17:06.447193Z"
    }
  ]
}
```

**Comment by maerteijn** [comment]
@ckepper Ah ok, I see now that the `price_excl_tax_excl_discounts` is also serialized in the line response (which means that we don't apply the offers before the response). This should be fixed (or we should leave out the `price_incl_tax_excl_discounts' and `price_excl_tax_excl_discounts` fields). I'll investigate this further and will realize a proper solution. Thanks for reporting!

**Comment by maerteijn** [comment]
I will try to fix this (when I have more time) in a proper way. In the meanwhile I have this branch which hopefully fixes this : https://github.com/django-oscar/django-oscar-api/tree/fix/update-line-quantity  Can I ask you try this (just to see if I'm lukcy :) )

**Comment by ckepper** [comment]
Thank you for supplying this patch so quickly. I tried it out but unfortunately it didn't fix it. I stepped through the code with a debugger and found that the correct value was in the result cache (`basket._lines._result_cache[0]`) but this was not used for the output.

**Comment by maerteijn** [comment]
Hi @ckepper, I think I fixed this in https://github.com/django-oscar/django-oscar-api/tree/fix/update-line-quantity now (and I added a test for it). Can you confirm this works for you? Then I'll review it next week and make a new release of oscarapi. Thnx.

**Comment by maerteijn** [comment]
@ckepper, We already made a proper solution for this and merged this to master. Maybe you can check this so we are sure we have the correct solution?
